### ISSUE TITLE
importing scrollzzz from 'scrollzzz' results in empty object returned

### ISSUE THREAD

**Issue by bovas85** [pldg/scrollzzz#1]
Hey there, I'm trying to import it as a module but all I get returned is {} 

It works fine while loading it as a script, but not when importing it via es6 module syntax

**Comment by bovas85** [comment]
importing 'scrollzzz/dist/scrollzzz.esm' works

**Comment by pldg** [comment]
Hi, thanks for the report! Are you using webpack? If so, this seems related to [#5756](https://github.com/webpack/webpack/issues/5756)

**Comment by bovas85** [comment]
Not sure :) most other libs I use including scrollama work as intended when using import

**Comment by bovas85** [comment]
I think it's due to the fact your main points to the browser iife rather than pointing to the main one
An example in scrollama:
https://github.com/russellgoldenberg/scrollama/blob/master/package.json

**Comment by bovas85** [comment]
based on this
https://medium.com/free-code-camp/anatomy-of-js-module-systems-and-building-libraries-fadcd8dbd0e
you'd need to export the UMD as main in package.json

**Comment by pldg** [comment]
I confirm the bug, it happens also when using Parcel bundler.

It's strange anyway, because I export three different bundles: _iife_ for browser (linked to [`pkg.browser`](https://docs.npmjs.com/files/package.json#browser)), _cjs_ for nodejs (linked to [`pkg.main`](https://docs.npmjs.com/files/package.json#main)), _es6_ the new import standard for modules (linked to [`pkg.module`](https://stackoverflow.com/questions/42708484/what-is-the-module-package-json-field-for)); it should be the bundler job to choose the correct build based on its configuration, I don't understand why this is not working.

Scrollama export only one bundle (_umd_) which works on both client and server side, which make things simpler. I'll add an _umd_ version and point it to `pkg.browser` fields, this should fix the issue.
